### ISSUE TITLE
Desenvolver área de Criação de Caronas

### ISSUE THREAD

**Issue by LeonardoPadre** [mdsreq-fga-unb/2023.1-UniBuddy#35]
# Descrição

- Desenvolver o frontend relacionado a criação de caronas, seguindo os critérios estabelecidos nas user stories.

# Objetivos

- [x] Desenvolver tela de criação de caronas
- [x] Integrar com o backend

# User Stories

- #24

**Comment by LeonardoPadre** [comment]
# Protótipo
![image](https://github.com/mdsreq-fga-unb/2023.1-UniBuddy/assets/62120616/5841a4dc-0cdd-4d00-bd77-077e3f3ba0a3)

**Comment by juanmangueira** [comment]
Issue finalizada.
